class Role:
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    FINANCE = "FINANCE"
    ADMIN = "ADMIN"
    ALL = (EMPLOYEE, MANAGER, FINANCE, ADMIN)


class ClaimStatus:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    MANAGER_APPROVED = "MANAGER_APPROVED"
    MANAGER_REJECTED = "MANAGER_REJECTED"
    FINANCE_VERIFIED = "FINANCE_VERIFIED"
    FINANCE_REJECTED = "FINANCE_REJECTED"
    REIMBURSED = "REIMBURSED"
    CANCELLED = "CANCELLED"
    TRANSITIONS = {
        DRAFT: {SUBMITTED, CANCELLED},
        SUBMITTED: {MANAGER_APPROVED, MANAGER_REJECTED, CANCELLED},
        MANAGER_APPROVED: {FINANCE_VERIFIED, FINANCE_REJECTED},
        FINANCE_VERIFIED: {REIMBURSED},
        MANAGER_REJECTED: set(),
        FINANCE_REJECTED: set(),
        REIMBURSED: set(),
        CANCELLED: set(),
    }

    @classmethod
    def can_move(cls, current, target):
        return target in cls.TRANSITIONS.get(current, set())

    EDITABLE = (DRAFT,)


class TravelStatus:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class Action:
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    VERIFIED = "VERIFIED"
    REIMBURSED = "REIMBURSED"
    CANCELLED = "CANCELLED"
